"""Secure HTML report generation for Sentrix analyses."""

from __future__ import annotations

import os
import tempfile
from html import escape
from pathlib import Path

from brand import BRAND


def _text(value: object, default: str = "Not available") -> str:
    """Return an HTML-safe display value for report content."""

    if value is None or value == "":
        return default
    return escape(str(value))


def generate_html_report(project, analysis, reports_dir: str | os.PathLike = "reports") -> str:
    """Generate an escaped, atomically-written HTML report.

    The optional ``reports_dir`` argument keeps the function compatible with
    existing callers while allowing production deployments to provide a
    configured persistent report directory.
    """

    output_dir = Path(reports_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    report_path = output_dir / f"analysis_{int(analysis.id)}.html"
    product_name = _text(BRAND.get("name", "Sentrix"))
    presented_by = _text(BRAND.get("presented_by", "HR-Presents"))

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{product_name} Analysis Report</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 40px; color: #172033; }}
main {{ max-width: 960px; margin: 0 auto; }}
table {{ width: 100%; border-collapse: collapse; margin-bottom: 24px; }}
th, td {{ border: 1px solid #dce2eb; padding: 10px; text-align: left; }}
th {{ background: #f5f7fa; width: 30%; }}
h1, h2 {{ color: #0d6efd; }}
.report-meta {{ color: #667085; margin-top: -10px; }}
.report-text {{ white-space: pre-wrap; overflow-wrap: anywhere; }}
footer {{ margin-top: 32px; color: #667085; font-size: 0.9rem; }}
</style>
</head>
<body>
<main>
<h1>{product_name} Analysis Report</h1>
<p class="report-meta">Presented by {presented_by}</p>

<h2>Project Information</h2>
<table>
<tr><th>Project</th><td>{_text(project.project_name)}</td></tr>
<tr><th>Original File</th><td>{_text(project.original_filename)}</td></tr>
<tr><th>Language</th><td>{_text(analysis.language)}</td></tr>
<tr><th>Date</th><td>{_text(analysis.created_at)}</td></tr>
</table>

<h2>Analysis Results</h2>
<table>
<tr><th>Overall Score</th><td>{_text(analysis.overall_score)}%</td></tr>
<tr><th>Pylint Score</th><td>{_text(analysis.pylint_score)}</td></tr>
<tr><th>Security Issues</th><td>{_text(analysis.security_count, "0")}</td></tr>
<tr><th>Complexity</th><td>{_text(analysis.complexity)}</td></tr>
<tr><th>Files</th><td>{_text(analysis.total_files, "0")}</td></tr>
<tr><th>Lines</th><td>{_text(analysis.total_lines, "0")}</td></tr>
<tr><th>Duration</th><td>{_text(analysis.analysis_duration)}</td></tr>
</table>

<h2>AI Summary</h2>
<div class="report-text">{_text(analysis.ai_summary)}</div>

<h2>Recommendations</h2>
<div class="report-text">{_text(analysis.recommendations)}</div>

<footer>Generated by {product_name}, presented by {presented_by}.</footer>
</main>
</body>
</html>
"""

    temporary_path: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=output_dir,
            prefix=f".{report_path.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary_file:
            temporary_file.write(html)
            temporary_file.flush()
            os.fsync(temporary_file.fileno())
            temporary_path = temporary_file.name

        os.replace(temporary_path, report_path)
    finally:
        if temporary_path and os.path.exists(temporary_path):
            os.remove(temporary_path)

    return str(report_path)
